# this manifest is used to deploy an horizontal pod autoscaler which scales couchDB deployment according to couchdb_httpd_database_reads_per_second metric

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: couchdb-hpa
  namespace: database
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-frontend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object 
    object:
      metric:
        name: couchdb_httpd_database_reads_per_second
      describedObject:
        apiVersion: batch/v1
        kind: Job
        name: couchdb_and_exporter-pod
      target:
        type: Value
        value: 0.5
