apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: httpgo-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpgo
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: myapphttp_test
      describedObject:
        apiVersion: batch/v1
        kind: Job
        name: httpgo-pod
      target:
        type: Value
        value: 0.5
