apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-exporter-deployment
  labels:
    app: process-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process-exporter
  template:
    metadata:
      labels:
        app: process-exporter
    spec:
      containers:
        - name: process-exporter
          image: ttedesch/process_exporter:v1.0curl_nocmd
          ports:
          - containerPort: 18000
          imagePullPolicy: Always
