global:
  scrape_interval: 10s
  evaluation_interval: 10s 

scrape_configs: 
  - job_name: 'httpgo-pod'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: httpgo
  - job_name: 'couchdb_and_exporter-pod'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: db-frontend
  - job_name: 'apache_and_exporter-pod'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: frontend
